version: '3.8'

services:
  backend:
    build: ./backend
    container_name: swabit-backend
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
      - MAX_USERS=${MAX_USERS:-10}
      - DB_PATH=/app/data/database.sqlite
    ports:
      - "3000:3000"
    volumes:
      - swabit-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: swabit-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  swabit-data:
    driver: local